auth:
  existingSecret: postgresql-auth
  secretKeys:
    adminPasswordKey: postgres-password
    userPasswordKey: password
  username: demo
  database: demo

primary:
  persistence:
    enabled: true
    storageClass: local-path
    size: 10Gi

  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: "1"
      memory: 1Gi

  startupProbe:
    enabled: true
  livenessProbe:
    enabled: true
  readinessProbe:
    enabled: true

architecture: standalone

service:
  type: ClusterIP