grafana:
  enabled: false

alertmanager:
  enabled: true

prometheusOperator:
  enabled: true

kubeStateMetrics:
  enabled: true

nodeExporter:
  enabled: true

prometheus:

  service:
    type: ClusterIP

  ingress:
    enabled: false

  prometheusSpec:

    retention: 7d

    scrapeInterval: 30s

    evaluationInterval: 30s

    serviceMonitorSelectorNilUsesHelmValues: false

    podMonitorSelectorNilUsesHelmValues: false

    resources:
      requests:
        cpu: 200m
        memory: 512Mi

      limits:
        cpu: 500m
        memory: 1Gi

    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
