replicas: 1

deploymentStrategy:
  type: RollingUpdate

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

ingress:
  enabled: true
  ingressClassName: traefik
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
  hosts:
    - grafana.local
  path: /
  pathType: Prefix

persistence:
  enabled: true
  type: pvc
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  size: 5Gi

resources:
  requests:
    cpu: 100m
    memory: 256Mi

  limits:
    cpu: 500m
    memory: 512Mi

env: {}

admin:
  existingSecret: grafana-admin
  userKey: admin-user
  passwordKey: admin-password

grafana.ini:
  server:
    root_url: http://grafana.local
  security:
    allow_embedding: true
  users:
    default_theme: light
  auth:
    disable_login_form: false
  analytics:
    reporting_enabled: false
    check_for_updates: false
  log:
    mode: console

  feature_toggles:
    enable: tempoSearch

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Tempo
        type: tempo
        access: proxy
        url: http://tempo:3100
        isDefault: false
        editable: true

sidecar:
  dashboards:
    enabled: true
    searchNamespace: ALL
  datasources:
    enabled: true

rbac:
  create: true

serviceAccount:
  create: true

readinessProbe:
  httpGet:
    path: /api/health
    port: 3000

livenessProbe:
  httpGet:
    path: /api/health
    port: 3000
